### ISSUE TITLE
Object + Distance --> __Table

### ISSUE THREAD

**Issue by zpace** [usmanwardag/HackDB#15]
in 02-sessions, change Object and Distance classes to Object_Table and Distance_Table, to make things clearer

(from AHW databases breakout)

**Comment by drphilmarshall** [comment]
I went back to this and decided that @usmanwardag had it right in the first place: each "Object" object really is representing an astronomical "object", whose data can be stored as a single row in the table called `object`. This table is set up (in `Base.metadata`) when the `Object` class is _declared_, and then any number of objects (from 0 to infinity) can then be `add`-ed to the table. So the correct name is `Object` and not `ObjectTable`.
