### ISSUE TITLE
Research alternative tutorials

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/HackDB#2]
Add links to md cell in notebook? Thanks @drarnakarick :-)

**Comment by jsobeck** [comment]
Alternative Tutorial: 
http://macrocosme.github.io/dotastronomy_seven.html?utm_content=bufferac2b7&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by jsobeck** [comment]
Additional Information:
http://docs.python-guide.org/en/latest/scenarios/db/?utm_content=buffer22bee&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#django-orm

**Comment by jsobeck** [comment]
SQL Keywords:
https://en.wikipedia.org/wiki/SQL#Queries

**Comment by drarnakarick** [comment]
Mode Analytic's SQL course is really good (and free!): https://community.modeanalytics.com.  Not really useful for this particular hack project (uses US census data),  but we could include a list of recommended websites/tutorials at the end of the notebook that people can go and look at after AHW:

**Comment by drphilmarshall** [comment]
Hey, Jen found this one too, its really nice: 

http://pythoncentral.io/sqlalchemy-orm-examples/

It shows how the joins work, and uses "Session" objects, which seem really powerful. We decided to keep the "Basics" notebook short, and started a second intro notebook for showing off these sessions in a very simple astronomical setting. We also started tutorial 3, which is where we can experiment with doing calculations with large simulated datasets. The idea there is to investigate wallclock time and memory useage for the simplest possible calculation. We can then imagine other notebooks later, that explore calculations using joined tables, specially designed indices etc. 

We can close this out for now then! :-)

**Comment by drphilmarshall** [comment]
These notes are nice too - from a 3 hour in-person tutorial given by the author of SQLAlchemy: 

http://www.jjinux.com/2014/04/pycon-notes-introduction-to-sqlalchemy.html

https://youtu.be/P141KRbxVKc?t=11m37s

**Comment by drarnakarick** [comment]
A nice talk by Paul Hancock at ICRAR: https://dl.dropboxusercontent.com/u/4038842/ANITA%20DB-SQL-Python.pdf will try to fold that into a new tutorial.

**Comment by drarnakarick** [comment]
Going to turn this [alternative tutorial](http://macrocosme.github.io/dotastronomy_seven.html?utm_content=bufferac2b7&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) into an IPython Notebook tutorial that can be added to AstroAlch_tutorial
