### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by drphilmarshall** [usmanwardag/HackDB#9]
@jsobeck and I like "MyFirstDatabase" but maybe we should also go for something with "astronomy" in it, because our target audience is astronomers who don't know how to make and use databases yet. Suggestions? Something that evokes simple/sqlalchemy/sqlite/astronomy. The problem is that names like "AstroDB" and "HackDB" make you think that we are working on a code package rather than a set of tutorials. Thinking in terms of course titles might help: "Simple Databases for Pythonic Astronomers"?

**Comment by drarnakarick** [comment]
"Simple Databases for Pythonic Astronomers" is a good title (e.g. for the README in GitHub and for the .ipyb).  'AstroSQLAlch_tutorial' (or similar) would work for the repo.

**Comment by jsobeck** [comment]
I like this suggestion from Phil.

Let's go with it.

**Comment by usmanwardag** [comment]
Done.
